/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./components/ArticleItem.vue')['default']
    BlogsItem: typeof import('./components/BlogsItem.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Header: typeof import('./components/Header.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
